config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :monthly_power_consumptions
  resources :consumers

  root :to => "consumers#index"

end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
	has_many :monthly_power_consumptions, dependent: :destroy
  CONSUMER_TYPES = %W(Household Industrial)

  def full_name
    first_name +  " " + middle_name + " " +last_name
  end
end

app/models/monthly_power_consumption.rb
class MonthlyPowerConsumption < ActiveRecord::Base
	belongs_to :consumer
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Devise helpers to set up a controller with user authentication
  before_action :authenticate_user!
end

app/controllers/consumers_controller.rb
class ConsumersController < ApplicationController
  before_action :set_consumer, only: [:show, :edit, :update, :destroy]

  # GET /consumers
  # GET /consumers.json
  def index
    @consumers = Consumer.all
  end

  # GET /consumers/1
  # GET /consumers/1.json
  def show
    #redirect_to "/consumers/#{params[:id]}/edit", consumer_id: params[:id], remote: true
  end

  # GET /consumers/new
  def new
    @consumer = Consumer.new
  end

  # GET /consumers/1/edit
  def edit
    @row_id = params[:id]
    respond_to do |format|
      format.js { render "edit"}
      format.html { render "edit"}
    end
  end

    # GET /consumers/1/edit
  def edit_monthly_consumptions
    @row_id = params[:id]
    respond_to do |format|
      format.js { render "edit"}
      format.html { render "edit"}
    end
  end

  # POST /consumers
  # POST /consumers.json
  def create
    @consumer = Consumer.new(consumer_params)

    respond_to do |format|
      if @consumer.save
        format.html { redirect_to @consumer, notice: 'Consumer was successfully created.' }
        format.json { render :show, status: :created, location: @consumer }
      else
        format.html { render :new }
        format.json { render json: @consumer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consumers/1
  # PATCH/PUT /consumers/1.json
  def update
    @row_id = params[:id]
    respond_to do |format|
      if @consumer.update(consumer_params)
        #format.html { redirect_to @consumer, notice: 'Consumer was successfully updated.' }
        #format.html { redirect_to '/', notice: 'Consumer was successfully updated.' }
        #format.json { render :show, status: :ok, location: @consumer }
        format.js { render "update_consumer_result_child_row.js.erb", consumer: @consumer, notice: 'Consumer was successfully updated.'}
      else
        #format.html { render :edit }
        #format.json { render json: @consumer.errors, status: :unprocessable_entity }
        format.js { render :file => "update_consumer_result_child_row.js.erb", consumer: @consumer }
      end
    end
  end

  # DELETE /consumers/1
  # DELETE /consumers/1.json
  def destroy
    @consumer.destroy
    respond_to do |format|
      format.html { redirect_to consumers_url, notice: 'Consumer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumer
      @consumer = Consumer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consumer_params
      params.require(:consumer).permit(:first_name, :middle_name, :last_name, :dob, :gender, :email, :phone1, :phone2, :address_1, :address_2, :city, :district, :state, :zipcode, :country, :consumer_type)
    end
end

app/controllers/monthly_power_consumptions_controller.rb
class MonthlyPowerConsumptionsController < ApplicationController
  before_action :set_monthly_power_consumption, only: [:show, :edit, :update, :destroy]

  # GET /monthly_power_consumptions
  # GET /monthly_power_consumptions.json
  def index
    @monthly_power_consumptions = MonthlyPowerConsumption.all
  end

  # GET /monthly_power_consumptions/1
  # GET /monthly_power_consumptions/1.json
  def show
  end

  # GET /monthly_power_consumptions/new
  def new
    @monthly_power_consumption = MonthlyPowerConsumption.new
  end

  # GET /monthly_power_consumptions/1/edit
  def edit
  end

  # POST /monthly_power_consumptions
  # POST /monthly_power_consumptions.json
  def create
    @monthly_power_consumption = MonthlyPowerConsumption.new(monthly_power_consumption_params)

    respond_to do |format|
      if @monthly_power_consumption.save
        format.html { redirect_to @monthly_power_consumption, notice: 'Monthly power consumption was successfully created.' }
        format.json { render :show, status: :created, location: @monthly_power_consumption }
      else
        format.html { render :new }
        format.json { render json: @monthly_power_consumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monthly_power_consumptions/1
  # PATCH/PUT /monthly_power_consumptions/1.json
  def update
    respond_to do |format|
      if @monthly_power_consumption.update(monthly_power_consumption_params)
        format.html { redirect_to @monthly_power_consumption, notice: 'Monthly power consumption was successfully updated.' }
        format.json { render :show, status: :ok, location: @monthly_power_consumption }
      else
        format.html { render :edit }
        format.json { render json: @monthly_power_consumption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monthly_power_consumptions/1
  # DELETE /monthly_power_consumptions/1.json
  def destroy
    @monthly_power_consumption.destroy
    respond_to do |format|
      format.html { redirect_to monthly_power_consumptions_url, notice: 'Monthly power consumption was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monthly_power_consumption
      @monthly_power_consumption = MonthlyPowerConsumption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monthly_power_consumption_params
      params.require(:monthly_power_consumption).permit(:kwhpm, :month_int, :year, :consumer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consumers_helper.rb
module ConsumersHelper
end

app/helpers/monthly_power_consumptions_helper.rb
module MonthlyPowerConsumptionsHelper
end

app/views/consumers/_edit_consumer_child_row.html.erb
<div class="container-fluid" style="background-color: #e3e3e3">
  <div class="col-xs-12">
    <h6 align = "center" class="text-primary"><i class="fa fa-edit fa-lg text-primary"></i> Editing Consumer</h6>
    <%= render 'form_consumer_child_row' %>
    <br />
    <%#= link_to 'Show', @consumer %>
    <%#= link_to 'Back', consumers_path %>
  </div>
</div>

app/views/consumers/_form.html.erb
    <%= simple_form_for(@consumer) do |f| %>
      <%= f.input :first_name %>
      <%= f.input :middle_name %>
      <%= f.input :last_name %>
      <%= f.input :dob, label: 'Date of Birth', as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 12 %>
      <%= f.input :email %>
      <%= f.input :phone1, label: 'Primary Phone'  %>
      <%= f.input :phone2, label: 'Secondary Phone' %>
      <%= f.input :address_1, label: 'Street Address' %>
      <%= f.input :city %>
      <%= f.input :district %>
      <%= f.input :consumer_type, collection: Consumer::CONSUMER_TYPES, label: "Consumer Type", include_blank: true, selected: @consumer.try(:consumer_type) %>
      <%= f.button :submit %>
    <% end %>

app/views/consumers/_form_consumer_child_row.html.erb
<%= simple_form_for(@consumer, remote: true)  do |f| %>
<table class="table table-bordered">
  <tr>
    <th>First Name</th>
    <th>Middle Name</th>
    <th>Last Name</th>   
  </tr>    
  <tr>
    <td><%= f.input :first_name, label: false %></td>
    <td><%= f.input :middle_name, label: false %></td>
    <td><%= f.input :last_name, label: false %></td>           
  </tr>
  <tr>
    <th>DOB</th>
    <th>Email</th>
    <th>Phone</th>   
  </tr>  
  <tr>
    <td><%= f.input :dob, label: false, as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 12 %></td>
    <td><%= f.input :email, label: false %></td>
    <td><%= f.input :phone1, label: false  %></td>           
  </tr>
  <tr>
    <th>Address</th>
    <th>District</th>
    <th>Consumer Type</th>   
  </tr> 
  <tr>
    <td><%= f.input :address_1, label: false%></td>
    <td><%= f.input :district, label: false %></td>
    <td><%= f.input :consumer_type, collection: Consumer::CONSUMER_TYPES, label: false, include_blank: true, selected: @consumer.try(:consumer_type) %></td>          
  </tr>
</table>
<div align="center"><%= f.button :submit, :class => "btn btn-primary", remote: true%></div>
<% end %>

app/views/consumers/_update_consumer_result_child_row.html.erb
<div class="container-fluid" style="background-color: #e3e3e3">
  <div class="col-xs-12">
    <h6 align = "center" class="text-primary"><i class="fa fa-edit fa-lg text-primary"></i> Editing Consumer</h6>
    <%= render 'form_consumer_child_row' %>
    <br />
    <%#= link_to 'Show', @consumer %>
    <%#= link_to 'Back', consumers_path %>
  </div>
</div>

app/views/consumers/edit.html.erb
<div class="container">
  <div class="col-xs-12 col-md-6">
    <h4><i class="fa fa-edit fa-lg"></i> Editing Consumer - <small><%=@consumer.full_name%></small></h4> <br /> 
    <%= render 'form' %>
    <br />
    <%= link_to 'Show', @consumer %> |
    <%= link_to 'Back', consumers_path %>
  </div>
</div>

app/views/consumers/edit.js.erb
var $parent_row = $("#consumer_action_<%= @row_id %>").closest('TR');
//var $parent_row = containing_row;
//var $parent_row = $(".table:first > tbody > tr:not(tr.child-row)").eq(<%= @row %>);

if ( $('tr.child-row:visible').length > 0 ) {
  $('tr.child-row:visible').remove();
  $("li>a:contains('Collapse Form')").addClass('disabled');

}

if ( $parent_row.next().hasClass('child-row') ) {
//
} 
else {
  $parent_row.after('<tr class="child-row"><td colspan="100"><%= j render "edit_consumer_child_row"%></td></tr>');
  // $("li>a:contains('Collapse Form')").eq(containing_row.index()).removeClass('disabled');
  // $('.dropdown.pull-right').removeClass('open');
}

app/views/consumers/index.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $('#consumer-table').DataTable({
      "oLanguage": {
        "sSearch": "SEARCH &nbsp;"
      }
    });
} );
</script>
<style>
.col-md-6 {
  text-align: right;
}
</style>
    <div class="container-fluid">

      <div class="col-sm" style="font-size: 14px;">
        <h4><i class="fa fa-users fa-lg"></i> Consumers</h4> 
        <table id="consumer-table" class="table table-striped table-bordered" cellspacing="0">
          <thead>
            <tr>
              <th>First name</th>
<!--               <th>Middle name</th> -->
              <th>Last name</th>
              <th>DOB</th>
<!--               <th>Gender</th> -->
              <th>Email</th>
              <th>Phone</th>
<!--               <th>Phone2</th> -->
              <th>Street Address</th>
<!--               <th>Address 2</th> -->
              <th>City</th>
              <th>District</th>
<!--               <th>State</th> -->
<!--               <th>Zipcode</th> -->
<!--               <th>Country</th> -->
              <th>Consumer type</th>
<!--               <th></th> -->
              <th></th>
<!--               <th></th> -->
<!--               <th></th> -->
            </tr>
          </thead>

          <tbody>
            <% @consumers.each do |consumer| %>
              <tr>
                <td><%= consumer.first_name %></td>
<!--                 <td><%= consumer.middle_name %></td> -->
                <td><%= consumer.last_name %></td>
                <td><%= consumer.dob %></td>
<!--                 <td><%= consumer.gender %></td> -->
                <td><%= consumer.email %></td>
                <td><%= consumer.phone1 %></td>
<!--                 <td><%= consumer.phone2 %></td> -->
                <td><%= consumer.address_1 %></td>
<!--                 <td><%= consumer.address_2 %></td> -->
                <td><%= consumer.city %></td>
                <td><%= consumer.district %></td>
<!--                 <td><%= consumer.state %></td> -->
<!--                 <td><%= consumer.zipcode %></td> -->
<!--                 <td><%= consumer.country %></td> -->
                <td><%= consumer.consumer_type %></td>
                <td>
                <%=
                dropdown = [
                           # Link Structure: ['Link Name', link_path(:params), 'link_type'], link_type can be 'ajax', 'static', or 'disabled'
                           ['Add Consumption', new_monthly_power_consumption_path(consumer: consumer.id),'ajax'],
                           ['View Consumptions', edit_monthly_power_consumption_path(consumer.id), 'ajax'],
                           ['Edit Consumer', edit_consumer_path(consumer, consumer_id: consumer.id), 'ajax']
                          ]
                render 'shared/datatable/consumer_action_dropdown', dropdowns: dropdown, consumer_id: consumer.id, formats: :html
                %>
                </td>
<!--                 <td><%#= link_to 'Edit', edit_consumer_path(consumer) %></td> -->
<!--            <td><%#= link_to 'Destroy', consumer, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'Add New Consumer', new_consumer_path, :class => "btn btn-primary" %>
      </div>

    </div><!-- /.container -->


<!-- <table id="consumer-table" class="table-striped display responsive no-wrap"> -->

app/views/consumers/new.html.erb
<div class="container">
  <div class="col-xs-12 col-md-6">
    <h4><i class="fa fa-user-plus fa-lg"></i> Add a Consumer </h4> <br/>
    <%= render 'form' %>
    <br/>
    <%= link_to 'Back', consumers_path %>
  </div>
</div>

app/views/consumers/show.html.erb
<p>
  <strong>First name:</strong>
  <%= @consumer.first_name %>
</p>

<p>
  <strong>Middle name:</strong>
  <%= @consumer.middle_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @consumer.last_name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @consumer.dob %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @consumer.gender %>
</p>

<p>
  <strong>Email:</strong>
  <%= @consumer.email %>
</p>

<p>
  <strong>Phone1:</strong>
  <%= @consumer.phone1 %>
</p>

<p>
  <strong>Phone2:</strong>
  <%= @consumer.phone2 %>
</p>

<p>
  <strong>Address 1:</strong>
  <%= @consumer.address_1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @consumer.address_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @consumer.city %>
</p>

<p>
  <strong>District:</strong>
  <%= @consumer.district %>
</p>

<p>
  <strong>State:</strong>
  <%= @consumer.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @consumer.zipcode %>
</p>

<p>
  <strong>Country:</strong>
  <%= @consumer.country %>
</p>

<p>
  <strong>Consumer type:</strong>
  <%= @consumer.consumer_type %>
</p>

<%= link_to 'Edit', edit_consumer_path(@consumer) %> |
<%= link_to 'Back', consumers_path %>

app/views/consumers/update_consumer_result_child_row.js.erb
var $parent_row = $("#consumer_action_<%= @row_id %>").closest('TR');
if ( $('tr.child-row:visible').length > 0 ) {
  $('tr.child-row:visible').remove();
  $("li>a:contains('Collapse Form')").addClass('disabled');

}
$parent_row.after('<tr class="child-row"><td colspan="100"><%= j render "edit_consumer_child_row"%></td></tr>');

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <a class="navbar-brand" href="#">Micro Hydro Financial Analyzer</a>
  <ul class="nav navbar-nav">
<!--     <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li> -->
    <li class="nav-item">
      <a class="nav-link" href="#">&nbsp;</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">&nbsp;</a>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="supportedContentDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Menu</a>
      <div class="dropdown-menu" aria-labelledby="supportedContentDropdown">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
      </div>
    </li>
  </ul>

  <div align="right">
    <span class="navbar-text text-muted">
      Padma Energy  &nbsp; <i class="fa fa-bolt fa-lg"></i>
    </span>
  </div>
  
  <div align="right">
    <% if user_signed_in? %>
      <li>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
      </li>
    <% else %>
      <li>
        <%= link_to('Login', new_user_session_path)  %>  
      </li>
    <% end %>
  </div>



</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MicroHydro</title>
  <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script><!-- Tether for Bootstrap -->
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<%=render partial: 'layouts/header'%>
<p class="notice"><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/monthly_power_consumptions/_form.html.erb
<%= form_for(@monthly_power_consumption) do |f| %>
  <% if @monthly_power_consumption.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monthly_power_consumption.errors.count, "error") %> prohibited this monthly_power_consumption from being saved:</h2>

      <ul>
      <% @monthly_power_consumption.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kwhpm %><br>
    <%= f.text_field :kwhpm %>
  </div>
  <div class="field">
    <%= f.label :month_int %><br>
    <%= f.number_field :month_int %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :consumer_id %><br>
    <%= f.number_field :consumer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monthly_power_consumptions/edit.html.erb
<h1>Editing Monthly Power Consumption</h1>

<%= render 'form' %>

<%= link_to 'Show', @monthly_power_consumption %> |
<%= link_to 'Back', monthly_power_consumptions_path %>

app/views/monthly_power_consumptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Monthly Power Consumptions</h1>

<table>
  <thead>
    <tr>
      <th>Kwhpm</th>
      <th>Month int</th>
      <th>Year</th>
      <th>Consumer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monthly_power_consumptions.each do |monthly_power_consumption| %>
      <tr>
        <td><%= monthly_power_consumption.kwhpm %></td>
        <td><%= monthly_power_consumption.month_int %></td>
        <td><%= monthly_power_consumption.year %></td>
        <td><%= monthly_power_consumption.consumer_id %></td>
        <td><%= link_to 'Show', monthly_power_consumption %></td>
        <td><%= link_to 'Edit', edit_monthly_power_consumption_path(monthly_power_consumption) %></td>
        <td><%= link_to 'Destroy', monthly_power_consumption, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monthly power consumption', new_monthly_power_consumption_path %>

app/views/monthly_power_consumptions/new.html.erb
<h1>New Monthly Power Consumption</h1>

<%= render 'form' %>

<%= link_to 'Back', monthly_power_consumptions_path %>

app/views/monthly_power_consumptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kwhpm:</strong>
  <%= @monthly_power_consumption.kwhpm %>
</p>

<p>
  <strong>Month int:</strong>
  <%= @monthly_power_consumption.month_int %>
</p>

<p>
  <strong>Year:</strong>
  <%= @monthly_power_consumption.year %>
</p>

<p>
  <strong>Consumer:</strong>
  <%= @monthly_power_consumption.consumer_id %>
</p>

<%= link_to 'Edit', edit_monthly_power_consumption_path(@monthly_power_consumption) %> |
<%= link_to 'Back', monthly_power_consumptions_path %>

app/views/shared/datatable/_consumer_action_dropdown.html.erb
<style>
.btn {
    /* display: inline-block; */
    /* font-weight: normal; */
    line-height: 0.6;
    /* text-align: center; */
    white-space: nowrap;
    vertical-align: middle;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    border: 1px solid transparent;
    padding: 0.5rem 1rem;
    font-size: 0.75rem;
    border-radius: 0.25rem;
}

.table th, .table td {
    padding: 0.3rem;
    /* vertical-align: top; */
    /* border-top: 1px solid #eceeef; */
}

</style>
<div class="consumer-actions-button dropdown pull-right" id="consumer_action_<%= consumer_id.to_s %>" >
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Actions 
    <span class="caret"></span>
  </button>
  
  <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
  <% dropdowns.each do |line| %>
    <!-- line[0] is Link Name (Eg: Add SEP)
         line[1] is Link Path
         line[2] is Link Type (ajax, static or disabled) -->
    <li >
      <%case line[2]%>
      <%when "disabled"%>
        <%= link_to line[0], line[1], class: "btn btn-default btn-xs", disabled: true%>
      <%when "static"%>
        <%= link_to line[0], line[1], class: "btn btn-default btn-xs" %>
      <%when "ajax"%>
        <%= link_to line[0], line[1], class: "btn btn-default btn-xs", remote: true %>
      <%end%>
    </li>
  <% end %>
  </ul>
</div>
<script>
  $("li>a:contains('Collapse Form')").addClass('disabled');
</script>